#!/usr/bin/env ruby

# Generate Samples

desc "generate doc.json using RDoc"
task :rdoc do
  #sh "shomen rdoc -T 'Fish Sampler' -m README README lib"
  #sh 'shomen rdoc -u "https://github.com/rubyworks/shomen/blob/master/work/sample" -m README README lib'
  sh 'shomen rdoc -m README lib [A-Z]*.*'
end

desc "generate doc.json using YARD"
task :yard do
  sh 'shomen yard --readme README lib - [A-Z]*.*'
end

