if RUBY_VERSION > '1.9'
  require_relative 'model/abstract'
  require_relative 'model/document'
  require_relative 'model/script'
  require_relative 'model/module'
  require_relative 'model/class'
  require_relative 'model/method'
  require_relative 'model/attribute'
# require_relative 'model/function'
  require_relative 'model/constant'
else
  require 'shomen/model/abstract'
  require 'shomen/model/document'
  require 'shomen/model/script'
  require 'shomen/model/module'
  require 'shomen/model/class'
  require 'shomen/model/method'
  require 'shomen/model/attribute'
# require 'shomen/model/function'
  require 'shomen/model/constant'
end
